// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQa4E8ZULWFKGwnsGjy8RmtxXTEkr1Jdk',
    appId: '1:911141855893:web:2d7c01129bbbfd453bf19c',
    messagingSenderId: '911141855893',
    projectId: 'chatapptute-67832',
    authDomain: 'chatapptute-67832.firebaseapp.com',
    storageBucket: 'chatapptute-67832.firebasestorage.app',
    measurementId: 'G-2Q5M6Q9JXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcj43NA8kacTAPdNwxGoR2OCJtGtWh-xM',
    appId: '1:911141855893:android:0ad4fe3e699d70903bf19c',
    messagingSenderId: '911141855893',
    projectId: 'chatapptute-67832',
    storageBucket: 'chatapptute-67832.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkhCMNf5xJAUIDHzDka7xDeGRncYZDlrw',
    appId: '1:911141855893:ios:d4b3ce3ae201f2333bf19c',
    messagingSenderId: '911141855893',
    projectId: 'chatapptute-67832',
    storageBucket: 'chatapptute-67832.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkhCMNf5xJAUIDHzDka7xDeGRncYZDlrw',
    appId: '1:911141855893:ios:d4b3ce3ae201f2333bf19c',
    messagingSenderId: '911141855893',
    projectId: 'chatapptute-67832',
    storageBucket: 'chatapptute-67832.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQa4E8ZULWFKGwnsGjy8RmtxXTEkr1Jdk',
    appId: '1:911141855893:web:9b870615c33b67c23bf19c',
    messagingSenderId: '911141855893',
    projectId: 'chatapptute-67832',
    authDomain: 'chatapptute-67832.firebaseapp.com',
    storageBucket: 'chatapptute-67832.firebasestorage.app',
    measurementId: 'G-NH72V4TYXG',
  );
}
